id: AA60BA620
title: 'The Sweet Song of Virtue and Auspiciousness: A Prayer for the Long Life of
  His Holiness the Fourteenth Dalai Lama'
type: translation
pechas:
- I445E55CB
- I7AFDE84B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:53.159295
  last_modified_at: 2023-01-04 11:53:53.159307
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I445E55CB/E439: 224E
  I7AFDE84B/0926: 224E
